In [2]:
import pandas as pd

data = pd.read_csv('../campus_placement/csv/campus_placement_data.csv')

data = data.drop(columns=['student_id', 'specialization'], axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   gender                      100000 non-null  object
 1   age                         100000 non-null  int64
 2   city_tier                   100000 non-null  object
 3   ssc_percentage              100000 non-null  float64
 4   ssc_board                   100000 non-null  object
 5   hsc_percentage              100000 non-null  float64
 6   hsc_board                   100000 non-null  object
 7   hsc_stream                  100000 non-null  object
 8   degree_percentage           100000 non-null  float64
 9   degree_field                100000 non-null  object
 10  mba_percentage              100000 non-null  float64
 11  internships_count           100000 non-null  int64
 12  projects_count              100000 non-null  int64
 13  certifications_count        100000 non-null  int64
 14  technical_skills_score      100000 non-null  float64
 15  soft_skills_score           100000 non-null  float64
 16  aptitude_score              100000 non-null  float64
 17  communication_score         100000 non-null  float64
 18  work_experience_months      100000 non-null  int64
 19  leadership_roles            100000 non-null  int64
 20  extracurricular_activities  100000 non-null  int64
 21  backlogs                    100000 non-null  int64
 22  placed                      100000 non-null  int64
 23  salary_lpa                  100000 non-null  float64
dtypes: float64(9), int64(9), object(6)
memory usage: 18.3+ MB

In [22]:
data.isna().sum()

gender                        0
age                           0
city_tier                     0
ssc_percentage                0
ssc_board                     0
hsc_percentage                0
hsc_board                     0
hsc_stream                    0
degree_percentage             0
degree_field                  0
mba_percentage                0
internships_count             0
projects_count                0
certifications_count          0
technical_skills_score        0
soft_skills_score             0
aptitude_score                0
communication_score           0
work_experience_months        0
leadership_roles              0
extracurricular_activities    0
backlogs                      0
placed                        0
salary_lpa                    0
dtype: int64

In [23]:
data = data.dropna()
data.isna().sum()

gender                        0
age                           0
city_tier                     0
ssc_percentage                0
ssc_board                     0
hsc_percentage                0
hsc_board                     0
hsc_stream                    0
degree_percentage             0
degree_field                  0
mba_percentage                0
internships_count             0
projects_count                0
certifications_count          0
technical_skills_score        0
soft_skills_score             0
aptitude_score                0
communication_score           0
work_experience_months        0
leadership_roles              0
extracurricular_activities    0
backlogs                      0
placed                        0
salary_lpa                    0
dtype: int64

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   gender                      100000 non-null  object
 1   age                         100000 non-null  int64
 2   city_tier                   100000 non-null  object
 3   ssc_percentage              100000 non-null  float64
 4   ssc_board                   100000 non-null  object
 5   hsc_percentage              100000 non-null  float64
 6   hsc_board                   100000 non-null  object
 7   hsc_stream                  100000 non-null  object
 8   degree_percentage           100000 non-null  float64
 9   degree_field                100000 non-null  object
 10  mba_percentage              100000 non-null  float64
 11  internships_count           100000 non-null  int64
 12  projects_count              100000 non-null  int64
 13  certifications_count        100000 non-null  int64
 14  technical_skills_score      100000 non-null  float64
 15  soft_skills_score           100000 non-null  float64
 16  aptitude_score              100000 non-null  float64
 17  communication_score         100000 non-null  float64
 18  work_experience_months      100000 non-null  int64
 19  leadership_roles            100000 non-null  int64
 20  extracurricular_activities  100000 non-null  int64
 21  backlogs                    100000 non-null  int64
 22  placed                      100000 non-null  int64
 23  salary_lpa                  100000 non-null  float64
dtypes: float64(9), int64(9), object(6)
memory usage: 18.3+ MB

In [3]:
data.head()

,gender,age,city_tier,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_stream,degree_percentage,degree_field,...,technical_skills_score,soft_skills_score,aptitude_score,communication_score,work_experience_months,leadership_roles,extracurricular_activities,backlogs,placed,salary_lpa
0,Male,22,Tier 1,71.01,State,76.76,CBSE,Commerce,64.44,Engineering,...,6.8,7.8,62.1,6.2,14,1,10,0,1,12.24
1,Female,22,Tier 2,58.46,CBSE,57.62,State,Science,68.24,Business,...,4.6,4.8,58.7,7.2,5,1,4,0,1,10.09
2,Female,21,Tier 1,67.83,CBSE,65.67,State,Commerce,52.33,Engineering,...,4.7,5.0,58.9,5.0,30,2,1,0,1,14.94
3,Female,21,Tier 2,80.40,CBSE,77.15,State,Science,56.55,Engineering,...,6.8,7.6,35.0,8.3,31,0,5,0,1,15.49
4,Male,21,Tier 1,66.10,State,62.81,ICSE,Science,78.93,Engineering,...,7.0,5.7,54.0,5.4,24,0,2,0,1,15.13

In [4]:
data.tail(30)

,gender,age,city_tier,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_stream,degree_percentage,degree_field,...,technical_skills_score,soft_skills_score,aptitude_score,communication_score,work_experience_months,leadership_roles,extracurricular_activities,backlogs,placed,salary_lpa
99970,Male,20,Tier 3,52.77,State,50.10,CBSE,Commerce,45.00,Business,...,9.6,10.0,44.6,9.3,0,0,1,0,1,7.14
99971,Male,22,Tier 1,74.82,CBSE,86.71,ICSE,Commerce,78.49,Business,...,6.6,6.6,71.2,8.7,0,3,5,0,1,13.53
99972,Female,24,Tier 1,82.63,CBSE,92.83,State,Science,83.31,Arts,...,6.6,4.2,23.6,4.3,18,1,6,0,1,12.76
99973,Other,18,Tier 1,100.00,State,100.00,ICSE,Science,100.00,Business,...,7.0,9.7,39.1,10.0,0,0,5,2,1,13.29
99974,Male,22,Tier 3,79.01,ICSE,85.39,State,Science,67.72,Engineering,...,5.7,5.2,72.1,2.4,0,1,0,0,1,10.75
99975,Female,20,Tier 2,62.30,State,61.94,State,Science,60.08,Engineering,...,9.5,8.4,44.1,8.2,19,0,0,1,1,10.08
99976,Female,22,Tier 1,74.97,CBSE,75.79,State,Science,77.32,Engineering,...,4.8,6.3,65.1,6.6,20,3,3,1,1,15.90
99977,Male,20,Tier 3,89.02,CBSE,92.92,State,Science,87.82,Other,...,2.3,3.7,86.0,4.1,11,3,4,1,1,10.25
99978,Male,24,Tier 2,76.82,ICSE,63.91,CBSE,Science,48.20,Engineering,...,2.8,1.0,34.3,1.0,13,0,1,1,0,0.00
99979,Female,20,Tier 2,91.69,State,78.21,State,Science,78.79,Arts,...,6.2,5.8,63.9,7.2,0,1,2,0,1,8.39
99980,Female,22,Tier 1,61.03,CBSE,54.21,CBSE,Science,45.00,Engineering,...,4.0,6.7,62.3,5.8,16,0,0,0,0,0.00
99981,Female,26,Tier 1,70.17,State,69.64,State,Commerce,71.09,Engineering,...,4.4,6.2,49.3,7.5,0,1,4,0,1,9.24
99982,Male,23,Tier 3,73.71,ICSE,75.88,CBSE,Arts,56.87,Engineering,...,2.8,4.4,31.5,4.0,6,0,5,0,0,0.00
99983,Male,24,Tier 2,82.66,State,94.03,CBSE,Science,76.04,Engineering,...,7.7,7.2,51.7,7.4,30,1,1,0,1,14.42
99984,Female,22,Tier 3,56.85,State,49.10,State,Commerce,45.00,Engineering,...,4.6,7.4,46.3,5.9,2,3,2,0,1,6.96
99985,Male,20,Tier 1,100.00,CBSE,100.00,ICSE,Science,88.65,Other,...,2.6,1.3,51.0,1.7,2,2,4,0,1,16.24
99986,Female,21,Tier 2,74.51,CBSE,74.56,CBSE,Science,84.80,Business,...,9.3,8.1,59.7,7.1,0,1,1,0,1,10.26
99987,Male,21,Tier 2,88.44,State,85.09,State,Commerce,72.10,Engineering,...,7.4,7.9,57.6,5.7,34,1,0,0,1,16.32
99988,Male,21,Tier 3,67.03,ICSE,71.19,CBSE,Science,72.34,Engineering,...,10.0,8.7,61.5,6.8,0,2,6,4,1,10.61
99989,Male,23,Tier 1,89.12,State,83.79,State,Science,85.52,Engineering,...,1.3,1.0,25.7,1.3,3,2,3,0,1,11.75
99990,Female,24,Tier 3,66.32,CBSE,70.79,CBSE,Science,82.85,Arts,...,1.8,3.4,48.8,5.6,36,2,2,4,0,0.00
99991,Male,23,Tier 1,68.48,State,69.65,CBSE,Arts,66.07,Engineering,...,5.3,2.4,61.8,2.4,6,0,5,6,0,0.00
99992,Female,21,Tier 3,72.78,State,78.32,State,Arts,71.76,Engineering,...,8.4,7.4,57.9,7.4,26,0,2,2,1,13.49
99993,Male,20,Tier 2,79.47,State,81.92,State,Arts,75.80,Engineering,...,4.7,5.2,56.7,4.0,4,1,0,1,0,0.00
99994,Female,19,Tier 3,76.76,CBSE,80.79,State,Commerce,80.31,Engineering,...,3.6,4.5,73.8,3.6,8,1,5,3,1,10.37
99995,Female,22,Tier 1,70.03,CBSE,58.73,State,Arts,48.01,Business,...,10.0,10.0,57.4,10.0,10,1,0,5,1,12.36
99996,Female,22,Tier 2,81.48,CBSE,65.48,State,Commerce,45.00,Engineering,...,6.0,8.4,56.5,9.2,7,2,4,0,1,10.64
99997,Female,20,Tier 2,79.29,State,70.13,State,Commerce,75.24,Engineering,...,6.6,7.0,38.0,7.1,10,1,4,1,1,13.05
99998,Male,22,Tier 1,74.81,CBSE,74.79,CBSE,Commerce,92.22,Arts,...,4.9,8.2,81.3,8.3,0,1,4,0,1,12.52
99999,Male,18,Tier 3,67.20,CBSE,66.32,ICSE,Commerce,67.83,Engineering,...,6.4,8.1,50.4,8.5,12,0,1,1,1,9.81

In [5]:
data.describe()

,age,ssc_percentage,hsc_percentage,degree_percentage,mba_percentage,internships_count,projects_count,certifications_count,technical_skills_score,soft_skills_score,aptitude_score,communication_score,work_experience_months,leadership_roles,extracurricular_activities,backlogs,placed,salary_lpa
count,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,21.55581,71.929885,71.831667,70.185520,22.853134,1.677490,3.295290,1.896330,5.982618,6.413043,59.913595,6.374366,9.964250,1.108080,2.931890,1.045870,0.844320,9.708429
std,1.50696,11.867225,13.903709,15.599274,31.610435,1.306627,1.870414,1.775324,1.948801,2.292634,17.772688,2.385099,11.953415,1.207242,1.937578,1.614606,0.362554,4.783668
min,18.00000,40.000000,40.000000,45.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,21.00000,63.870000,62.120000,58.090000,0.000000,1.000000,2.000000,0.000000,4.600000,4.800000,47.900000,4.700000,0.000000,0.000000,2.000000,0.000000,1.000000,8.510000
50%,21.00000,71.920000,71.860000,69.890000,0.000000,1.000000,3.000000,1.000000,6.000000,6.500000,60.000000,6.500000,3.000000,1.000000,3.000000,0.000000,1.000000,10.710000
75%,22.00000,80.030000,81.720000,81.840000,59.330000,2.000000,4.000000,3.000000,7.300000,8.200000,72.100000,8.300000,20.000000,2.000000,4.000000,2.000000,1.000000,12.710000
max,26.00000,100.000000,100.000000,100.000000,100.000000,5.000000,10.000000,8.000000,10.000000,10.000000,100.000000,10.000000,36.000000,5.000000,10.000000,10.000000,1.000000,24.220000

In [26]:
X = data.drop(columns=['placed', 'salary_lpa'], axis=1)

In [27]:
y = data['placed']
y.shape

(100000,)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    random_state=42, stratify=y)

In [29]:
unranked_cat_feature = X.select_dtypes(include='object').columns
num_feature = X.select_dtypes(exclude='object').columns
unranked_cat_feature = unranked_cat_feature.drop('city_tier')
ranked_cat_feature = X.select_dtypes(include='object').columns
ranked_cat_feature = ranked_cat_feature.drop(['gender', 'ssc_board', 'hsc_board',
                                              'hsc_stream', 'degree_field'])

In [30]:
unranked_cat_feature

Index(['gender', 'ssc_board', 'hsc_board', 'hsc_stream', 'degree_field'], dtype='object')

In [31]:
num_feature

Index(['age', 'ssc_percentage', 'hsc_percentage', 'degree_percentage',
       'mba_percentage', 'internships_count', 'projects_count',
       'certifications_count', 'technical_skills_score', 'soft_skills_score',
       'aptitude_score', 'communication_score', 'work_experience_months',
       'leadership_roles', 'extracurricular_activities', 'backlogs'],
      dtype='object')

In [32]:
ranked_cat_feature

Index(['city_tier'], dtype='object')

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   gender                      100000 non-null  object
 1   age                         100000 non-null  int64
 2   city_tier                   100000 non-null  object
 3   ssc_percentage              100000 non-null  float64
 4   ssc_board                   100000 non-null  object
 5   hsc_percentage              100000 non-null  float64
 6   hsc_board                   100000 non-null  object
 7   hsc_stream                  100000 non-null  object
 8   degree_percentage           100000 non-null  float64
 9   degree_field                100000 non-null  object
 10  mba_percentage              100000 non-null  float64
 11  internships_count           100000 non-null  int64
 12  projects_count              100000 non-null  int64
 13  certifications_count        100000 non-null  int64
 14  technical_skills_score      100000 non-null  float64
 15  soft_skills_score           100000 non-null  float64
 16  aptitude_score              100000 non-null  float64
 17  communication_score         100000 non-null  float64
 18  work_experience_months      100000 non-null  int64
 19  leadership_roles            100000 non-null  int64
 20  extracurricular_activities  100000 non-null  int64
 21  backlogs                    100000 non-null  int64
 22  placed                      100000 non-null  int64
 23  salary_lpa                  100000 non-null  float64
dtypes: float64(9), int64(9), object(6)
memory usage: 18.3+ MB

In [34]:
data.tail(n=20)

,gender,age,city_tier,ssc_percentage,ssc_board,hsc_percentage,hsc_board,hsc_stream,degree_percentage,degree_field,...,technical_skills_score,soft_skills_score,aptitude_score,communication_score,work_experience_months,leadership_roles,extracurricular_activities,backlogs,placed,salary_lpa
99980,Female,22,Tier 1,61.03,CBSE,54.21,CBSE,Science,45.00,Engineering,...,4.0,6.7,62.3,5.8,16,0,0,0,0,0.00
99981,Female,26,Tier 1,70.17,State,69.64,State,Commerce,71.09,Engineering,...,4.4,6.2,49.3,7.5,0,1,4,0,1,9.24
99982,Male,23,Tier 3,73.71,ICSE,75.88,CBSE,Arts,56.87,Engineering,...,2.8,4.4,31.5,4.0,6,0,5,0,0,0.00
99983,Male,24,Tier 2,82.66,State,94.03,CBSE,Science,76.04,Engineering,...,7.7,7.2,51.7,7.4,30,1,1,0,1,14.42
99984,Female,22,Tier 3,56.85,State,49.10,State,Commerce,45.00,Engineering,...,4.6,7.4,46.3,5.9,2,3,2,0,1,6.96
99985,Male,20,Tier 1,100.00,CBSE,100.00,ICSE,Science,88.65,Other,...,2.6,1.3,51.0,1.7,2,2,4,0,1,16.24
99986,Female,21,Tier 2,74.51,CBSE,74.56,CBSE,Science,84.80,Business,...,9.3,8.1,59.7,7.1,0,1,1,0,1,10.26
99987,Male,21,Tier 2,88.44,State,85.09,State,Commerce,72.10,Engineering,...,7.4,7.9,57.6,5.7,34,1,0,0,1,16.32
99988,Male,21,Tier 3,67.03,ICSE,71.19,CBSE,Science,72.34,Engineering,...,10.0,8.7,61.5,6.8,0,2,6,4,1,10.61
99989,Male,23,Tier 1,89.12,State,83.79,State,Science,85.52,Engineering,...,1.3,1.0,25.7,1.3,3,2,3,0,1,11.75
99990,Female,24,Tier 3,66.32,CBSE,70.79,CBSE,Science,82.85,Arts,...,1.8,3.4,48.8,5.6,36,2,2,4,0,0.00
99991,Male,23,Tier 1,68.48,State,69.65,CBSE,Arts,66.07,Engineering,...,5.3,2.4,61.8,2.4,6,0,5,6,0,0.00
99992,Female,21,Tier 3,72.78,State,78.32,State,Arts,71.76,Engineering,...,8.4,7.4,57.9,7.4,26,0,2,2,1,13.49
99993,Male,20,Tier 2,79.47,State,81.92,State,Arts,75.80,Engineering,...,4.7,5.2,56.7,4.0,4,1,0,1,0,0.00
99994,Female,19,Tier 3,76.76,CBSE,80.79,State,Commerce,80.31,Engineering,...,3.6,4.5,73.8,3.6,8,1,5,3,1,10.37
99995,Female,22,Tier 1,70.03,CBSE,58.73,State,Arts,48.01,Business,...,10.0,10.0,57.4,10.0,10,1,0,5,1,12.36
99996,Female,22,Tier 2,81.48,CBSE,65.48,State,Commerce,45.00,Engineering,...,6.0,8.4,56.5,9.2,7,2,4,0,1,10.64
99997,Female,20,Tier 2,79.29,State,70.13,State,Commerce,75.24,Engineering,...,6.6,7.0,38.0,7.1,10,1,4,1,1,13.05
99998,Male,22,Tier 1,74.81,CBSE,74.79,CBSE,Commerce,92.22,Arts,...,4.9,8.2,81.3,8.3,0,1,4,0,1,12.52
99999,Male,18,Tier 3,67.20,CBSE,66.32,ICSE,Commerce,67.83,Engineering,...,6.4,8.1,50.4,8.5,12,0,1,1,1,9.81

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ('ranked_cat_transformer', OrdinalEncoder(), ranked_cat_feature),
        ('unranked_cat_transformer', OneHotEncoder(), unranked_cat_feature),
        ('num_transformer', StandardScaler(), num_feature)
    ]
)

In [36]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

models = {
    'random_forest': RandomForestClassifier(random_state=42,n_jobs=-1),
    'decision_tree': DecisionTreeClassifier(random_state=42),
    'logistic_regression': LogisticRegression(random_state=42,n_jobs=-1),
    'sgd_classifier': SGDClassifier(random_state=42,n_jobs=-1),
    'knn_classifier': KNeighborsClassifier(),
    'extra_tree': ExtraTreeClassifier(random_state=42),
    'svc': SVC(random_state=42),
    'adaboost': AdaBoostClassifier(random_state=42)
}

In [38]:
from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score, recall_score, confusion_matrix, accuracy_score, precision_score

results = {}

for model_name, model in models.items():
  pipeline = Pipeline(steps=[
      ('preprocessor', preprocessor),
       ('model', model)
       ])
  pipeline.fit(X_train, y_train)
  y_pred = pipeline.predict(X_test)
  results[model_name] = {
    "F1": f1_score(y_test, y_pred),
    "Recall": recall_score(y_test, y_pred),
    "Accuracy": accuracy_score(y_test, y_pred),
    "Confusion Matrix" : confusion_matrix(y_test, y_pred),
    "Precision": precision_score(y_test, y_pred)
    }

resulf_df = pd.DataFrame(results)
print(resulf_df.T.round(4).sort_values(by='Recall', ascending=False))

/usr/lib/python3/dist-packages/sklearn/ensemble/_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

                           F1    Recall Accuracy  \
svc                  0.920367  0.986971   0.8558
random_forest        0.918682  0.980813   0.8534
sgd_classifier       0.920126  0.979983  0.85635
logistic_regression  0.920609   0.97033   0.8587
adaboost             0.919907  0.968909  0.85755
knn_classifier       0.909604  0.953749  0.83995
decision_tree        0.871651  0.866102  0.78465
extra_tree           0.867256  0.862608  0.77705

                                  Confusion Matrix Precision
svc                    [[450, 2664], [220, 16666]]  0.862183
random_forest          [[506, 2608], [324, 16562]]  0.863954
sgd_classifier         [[579, 2535], [338, 16548]]  0.867159
logistic_regression    [[789, 2325], [501, 16385]]  0.875735
adaboost               [[790, 2324], [525, 16361]]  0.875622
knn_classifier         [[694, 2420], [781, 16105]]  0.869366
decision_tree        [[1068, 2046], [2261, 14625]]  0.877272
extra_tree            [[975, 2139], [2320, 14566]]  0.871955

In [ ]:
best_model_pipeline  = Pipeline(
    [("preprocessor", preprocessor),
     ("best_model", SVC())]
)

best_model_pipeline = best_model_pipeline.fit(X_train, y_train)

In [ ]:
best_model_pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('ranked_cat_transformer',
                                                  OrdinalEncoder(),
                                                  Index(['city_tier'], dtype='object')),
                                                 ('unranked_cat_transformer',
                                                  OneHotEncoder(),
                                                  Index(['gender', 'ssc_board', 'hsc_board', 'hsc_stream', 'degree_field'], dtype='object')),
                                                 ('num_transformer',
                                                  StandardScaler(),
                                                  Index(['age', 'ssc_percentage', 'hsc_percentage', 'degree_percentage',
       'mba_percentage', 'internships_count', 'projects_count',
       'certifications_count', 'technical_skills_score', 'soft_skills_score',
       'aptitude_score', 'communication_score', 'work_experience_months',
       'leadership_roles', 'extracurricular_activities', 'backlogs'],
      dtype='object'))])),
                ('best_model', SVC())])

In [ ]:
import joblib
from pathlib import Path

MODEL_DIR = Path("models")
MODEL_DIR.mkdir(exist_ok=True)
joblib.dump(best_model_pipeline, "models/best_model.pkl")

['models/best_model.pkl']